/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["src/**/*.{ts,tsx}", "components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
        xl: `calc(var(--1rem) * 0.75)`,
        '2xl': `var(--1rem)`,
        '3xl': `calc(var(--1rem) * 1.5)`,
      },
      columns: {
        '3xs': `calc(var(--1rem) * 16)`,
        '2xs': 'calc(var(--1rem) * 18)',
        xs: 'calc(var(--1rem) * 20)',
        sm: 'calc(var(--1rem) * 24)',
        md: 'calc(var(--1rem) * 28)',
        lg: 'calc(var(--1rem) * 32)',
        xl: 'calc(var(--1rem) * 36)',
        '2xl': 'calc(var(--1rem) * 42)',
        '3xl': 'calc(var(--1rem) * 48)',
        '4xl': 'calc(var(--1rem) * 56)',
        '5xl': 'calc(var(--1rem) * 64)',
        '6xl': 'calc(var(--1rem) * 72)',
        '7xl': 'calc(var(--1rem) * 80)',
      },
      fontSize: {
        xs: [`calc(var(--1rem) * 0.75)`, { lineHeight: `calc(var(--1rem) * 1)` }],
        sm: [`calc(var(--1rem) * 0.875)`, { lineHeight: `calc(var(--1rem) * 1.25)` }],
        base: [`calc(var(--1rem) * 1)`, { lineHeight: `calc(var(--1rem) * 1.5)` }],
        lg: [`calc(var(--1rem) * 1.123)`, { lineHeight: `calc(var(--1rem) * 1.75)` }],
        xl: [`calc(var(--1rem) * 1.25)`, { lineHeight: `calc(var(--1rem) * 1.75)` }],
        '2xl': [`calc(var(--1rem) * 1.5)`, { lineHeight: `calc(var(--1rem) * 2)` }],
        '3xl': [`calc(var(--1rem) * 1.875)`, { lineHeight: `calc(var(--1rem) * 2.25)` }],
        '4xl': [`calc(var(--1rem) * 2.25)`, { lineHeight: `calc(var(--1rem) * 2.5)` }],
        '5xl': [`calc(var(--1rem) * 3)`, { lineHeight: 1 }],
        '6xl': [`calc(var(--1rem) * 3.75)`, { lineHeight: 1 }],
        '7xl': [`calc(var(--1rem) * 4.5)`, { lineHeight: 1 }],
        '8xl': [`calc(var(--1rem) * 6)`, { lineHeight: 1 }],
        '9xl': [`calc(var(--1rem) * 8)`, { lineHeight: 1 }],
      },
      lineHeight: {
        3: `calc(var(--1rem) * 0.75)`,
        4: `calc(var(--1rem) * 1)`,
        5: `calc(var(--1rem) * 1.25)`,
        6: `calc(var(--1rem) * 1.5)`,
        7: `calc(var(--1rem) * 1.75)`,
        8: `calc(var(--1rem) * 2)`,
        9: `calc(var(--1rem) * 2.25)`,
        10: `calc(var(--1rem) * 2.5)`,
      },
      maxWidth: ({ theme, breakpoints }) => ({
        ...theme('spacing'),
        none: 'none',
        xs: `calc(var(--1rem) * 20)`,
        sm: `calc(var(--1rem) * 24)`,
        md: `calc(var(--1rem) * 28)`,
        lg: `calc(var(--1rem) * 32)`,
        xl: `calc(var(--1rem) * 36)`,
        '2xl': `calc(var(--1rem) * 42)`,
        '3xl': `calc(var(--1rem) * 48)`,
        '4xl': `calc(var(--1rem) * 56)`,
        '5xl': `calc(var(--1rem) * 54)`,
        '6xl': `calc(var(--1rem) * 72)`,
        '7xl': `calc(var(--1rem) * 80)`,
        full: '100%',
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
        prose: '65ch',
        ...breakpoints(theme('screens')),
      }),
      spacing: {
        0.5: `calc(var(--1rem) * 0.125)`,
        1: `calc(var(--1rem) * 0.25)`,
        1.5: `calc(var(--1rem) * 0.375)`,
        2: `calc(var(--1rem) * 0.5)`,
        2.5: `calc(var(--1rem) * 0.625)`,
        3: `calc(var(--1rem) * 0.75)`,
        3.5: `calc(var(--1rem) * 0.875)`,
        4: `calc(var(--1rem) * 1)`,
        5: `calc(var(--1rem) * 1.25)`,
        6: `calc(var(--1rem) * 1.5)`,
        7: `calc(var(--1rem) * 1.75)`,
        8: `calc(var(--1rem) * 2)`,
        9: `calc(var(--1rem) * 2.25)`,
        10: `calc(var(--1rem) * 2.5)`,
        11: `calc(var(--1rem) * 2.75)`,
        12: `calc(var(--1rem) * 3)`,
        14: `calc(var(--1rem) * 3.5)`,
        16: `calc(var(--1rem) * 4)`,
        20: `calc(var(--1rem) * 5)`,
        24: `calc(var(--1rem) * 6)`,
        28: `calc(var(--1rem) * 7)`,
        32: `calc(var(--1rem) * 8)`,
        36: `calc(var(--1rem) * 9)`,
        40: `calc(var(--1rem) * 10)`,
        44: `calc(var(--1rem) * 11)`,
        48: `calc(var(--1rem) * 12)`,
        52: `calc(var(--1rem) * 13)`,
        56: `calc(var(--1rem) * 14)`,
        60: `calc(var(--1rem) * 15)`,
        64: `calc(var(--1rem) * 16)`,
        72: `calc(var(--1rem) * 18)`,
        80: `calc(var(--1rem) * 20)`,
        96: `calc(var(--1rem) * 24)`
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}
